name: 部署到 GitHub Pages

on:
  # 每次推送到 `main` 分支时触发这个工作流程
  # 如果你使用了别的分支名，请按需将 `main` 替换成你的分支名
  push:
    branches: [ main ]
  # 允许你在 GitHub 上的 Actions 标签页中手动触发此工作流程
  workflow_dispatch:

# 允许任务克隆仓库并创建一个页面部署
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 使用 git 检出仓库
        uses: actions/checkout@v5
      - name: 安装、构建并上传你的站点
        uses: withastro/action@v5
        # with:
          # path: . # 仓库中 Astro 项目的根目录位置。（可选）
          # node-version: 20 # 用于构建站点的特定 Node.js 版本，默认为 20。（可选）
          # package-manager: pnpm@latest # 指定用于安装依赖项和构建站点的 Node.js 包管理器。会自动根据仓库中的 lockfile 进行检测。（可选）
          # build-cmd: pnpm run build # 用于构建你的网站的命令。默认运行软件包的构建脚本或任务。（可选）
        # env:
          # PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # 环境变量值请使用单引号。（可选）

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
